---
region: "eu-west-2"
component: "grafana"

private_network_cidr: "10.0.0.0/16"

database_instance_type: "db.t3.micro"
database_version: "12.3"

allocated_storage: 16

use_encrypted_storage: "true"
use_multiple_availability_zones: "true"

state_bucket_name: "infrablocks-%{hiera('component')}-%{deployment_identifier}"
secrets_bucket_name: "%{hiera('state_bucket_name')}"

domain_state_bucket_region: "%{hiera('region')}"
domain_state_bucket_name: "%{hiera('state_bucket_name')}"
domain_state_bucket_is_encrypted: "true"
domain_state_key: "domain/deployments/%{deployment_identifier}.tfstate"

certificate_state_bucket_region: "%{hiera('region')}"
certificate_state_bucket_name: "%{hiera('state_bucket_name')}"
certificate_state_bucket_is_encrypted: "true"
certificate_state_key: "certificate/deployments/%{deployment_identifier}.tfstate"

network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_name: "%{hiera('state_bucket_name')}"
network_state_bucket_is_encrypted: "true"
network_state_key: "network/deployments/%{deployment_identifier}.tfstate"

cluster_state_bucket_region: "%{hiera('region')}"
cluster_state_bucket_name: "%{hiera('state_bucket_name')}"
cluster_state_bucket_is_encrypted: "true"
cluster_state_key: "cluster/deployments/%{deployment_identifier}.tfstate"

database_state_bucket_region: "%{hiera('region')}"
database_state_bucket_name: "%{hiera('state_bucket_name')}"
database_state_bucket_is_encrypted: "true"
database_state_key: "database/deployments/%{deployment_identifier}.tfstate"

service_state_bucket_region: "%{hiera('region')}"
service_state_bucket_name: "%{hiera('state_bucket_name')}"
service_state_bucket_is_encrypted: "true"
service_state_key: "service/deployments/%{deployment_identifier}.tfstate"
