---
vars:
  region: "%{hiera('region')}"

  domain_name: "%{hiera('domain_name')}"

  domain_state_key: "%{hiera('domain_state_key')}"
  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"

backend_config:
  key: "%{hiera('certificate_state_key')}"
  bucket: "%{hiera('certificate_state_bucket_name')}"
  region: "%{hiera('certificate_state_bucket_region')}"
  encrypt: "%{hiera('certificate_state_bucket_is_encrypted')}"
