---
vars:
  grafana_user: "%{hiera('grafana_admin_user')}"
  grafana_password: "%{hiera('grafana_admin_password')}"

  service_state_key: "%{hiera('service_state_key')}"
  service_state_bucket_name: "%{hiera('service_state_bucket_name')}"
  service_state_bucket_region: "%{hiera('service_state_bucket_region')}"

backend_config:
  key: "%{hiera('configuration_state_key')}"
  bucket: "%{hiera('configuration_state_bucket_name')}"
  region: "%{hiera('configuration_state_bucket_region')}"
  encrypt: "%{hiera('configuration_state_bucket_is_encrypted')}"
