---
vars:
  region: "%{hiera('region')}"
  private_network_cidr: "%{hiera('private_network_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  database_instance_type: "%{hiera('database_instance_type')}"
  database_version: "%{hiera('database_version')}"
  database_name: "%{hiera('database_name')}"
  database_master_user: "%{hiera('database_user')}"
  database_master_user_password: "%{hiera('database_password')}"

  allocated_storage: "%{hiera('allocated_storage')}"

  use_encrypted_storage: "%{hiera('use_encrypted_storage')}"
  use_multiple_availability_zones: "%{hiera('use_multiple_availability_zones')}"

  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_key: "%{hiera('network_state_key')}"
  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"

backend_config:
  bucket: "%{hiera('database_state_bucket_name')}"
  key: "%{hiera('database_state_key')}"
  region: "%{hiera('database_state_bucket_region')}"
  encrypt: "%{hiera('database_state_bucket_is_encrypted')}"
