---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  domain_name: "%{hiera('domain_name')}"

  service_desired_count: 3

  secrets_bucket_name: "%{hiera('secrets_bucket_name')}"

  database_name: "%{hiera('database_name')}"
  database_user: "%{hiera('database_user')}"
  database_password: "%{hiera('database_password')}"

  grafana_image: "infrablocks/grafana-aws:0.3.0"
  grafana_service_container_port: "3001"
  grafana_service_host_port: "3001"
  grafana_service_lb_port: "3001"
  grafana_admin_user: "%{hiera('grafana_admin_user')}"
  grafana_admin_password: "%{hiera('grafana_admin_password')}"
  grafana_allow_cidrs:
    - "0.0.0.0/0"

  domain_state_key: "%{hiera('domain_state_key')}"
  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"

  network_state_key: "%{hiera('network_state_key')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"

  database_state_key: "%{hiera('database_state_key')}"
  database_state_bucket_name: "%{hiera('database_state_bucket_name')}"
  database_state_bucket_region: "%{hiera('database_state_bucket_region')}"

  cluster_state_key: "%{hiera('cluster_state_key')}"
  cluster_state_bucket_name: "%{hiera('cluster_state_bucket_name')}"
  cluster_state_bucket_region: "%{hiera('cluster_state_bucket_region')}"

backend_config:
  key: "%{hiera('service_state_key')}"
  bucket: "%{hiera('service_state_bucket_name')}"
  region: "%{hiera('service_state_bucket_region')}"
  encrypt: "%{hiera('service_state_bucket_is_encrypted')}"
